public class RedressDomain {
private RedressService service = new RedressService();
	public void beforeUpdate(List<Redress__c> records, Map<Id, Redress__c> oldRecords)
    {
    }
    
    public void beforeInsert(List<Redress__c> records)
    {
    }

    public void afterUpdate(List<Redress__c> records, Map<Id, Redress__c> oldRecords)
    {
    }
    
    public void afterInsert(List<Redress__c> records)
    {
    }
    
    public void afterDelete(List<Redress__c> records)
    {
    }
    
    

}