public without sharing class TerritoryService
{
    public static final Integer FSA_CHAR_LENGTH          = 3;
    public static final String TERRITORY_BANK            = 'Bank';
    public static final String TERRITORY_MORTGAGE_BROKER = 'Mortgage Broker';
    public static final String TERRITORY_WEALTH          = 'Wealth Partner';

    public enum Partner_Channel {BANK, MORTGAGE, WEALTH}
    
    public TerritoryService() {}
}